In [2]:
import cv2
import os
import numpy as np
import os.path as osp
import matplotlib.pyplot as plt
import torch
import torch.nn as nn
from torch.nn import Module
import torch.nn.functional as F
from torch.nn.modules.padding import ReplicationPad2d
import glob
# from tensorboardX import SummaryWriter
from torch.utils.tensorboard import SummaryWriter
import re
import mylib.polSAR_utils as psr
from mylib import types
import torchvision
from ptsemseg.models import my_resnet
import yaml
from mylib import types
from typing import Optional
from torch import Tensor

SyntaxError: invalid syntax (polSAR_utils.py, line 805)

In [4]:
a = np.arange(24).reshape(2, 3, 4)
b = np.arange(25, 49).reshape(2, 3, 4)
a, b

(array([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],
 
        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]]),
 array([[[25, 26, 27, 28],
         [29, 30, 31, 32],
         [33, 34, 35, 36]],
 
        [[37, 38, 39, 40],
         [41, 42, 43, 44],
         [45, 46, 47, 48]]]))

In [10]:
c = np.einsum('ijk, abc->iak', a, b)
c.shape

(2, 2, 4)

In [27]:
c = a()
c._a__b
setattr(c, '_a__b', 5)
c._a__b

5

In [3]:
a = torch.tensor([1+2j, 3+4j]).view(1,1,1,1,2)
a, a.abs()

(tensor([[[[[1.+2.j, 3.+4.j]]]]]), tensor([[[[[2.2361, 5.0000]]]]]))

In [13]:
np.angle(np.array([100,1, 1+1j, 10000j, -1, -1-1j, -1j, 3-3j]).reshape(1,1,1,1,1,2,-1))

array([[[[[[[ 0.        ,  0.        ,  0.78539816,  1.57079633],
            [ 3.14159265, -2.35619449, -1.57079633, -0.78539816]]]]]]])

In [18]:

class ComplexUpsample(Module):
    def __init__(self, size = None, scale_factor = None,
                 mode: str = 'nearest', align_corners: Optional[bool] = None) -> None:
        super().__init__()
        self.up = nn.Upsample(size=size, scale_factor=scale_factor, mode=mode, align_corners=align_corners)
        
    def forward(self, input: Tensor) -> Tensor:
        if 'complex' not in str(input.dtype):
            raise ValueError('not support non-complex data')
        real = self.up(input.real)
        imag = self.up(input.imag)
        return real + 1j*imag

In [20]:
a = torch.tensor([[1,2],[3,4]])+1j*torch.tensor([[8,6],[7,5]]).view(1,1,2,2)
b = ComplexUpsample(scale_factor=2, mode='bilinear')
a,b(a)

(tensor([[[[1.+8.j, 2.+6.j],
           [3.+7.j, 4.+5.j]]]]),
 tensor([[[[1.0000+8.0000j, 1.2500+7.5000j, 1.7500+6.5000j, 2.0000+6.0000j],
           [1.5000+7.7500j, 1.7500+7.2500j, 2.2500+6.2500j, 2.5000+5.7500j],
           [2.5000+7.2500j, 2.7500+6.7500j, 3.2500+5.7500j, 3.5000+5.2500j],
           [3.0000+7.0000j, 3.2500+6.5000j, 3.7500+5.5000j, 4.0000+5.0000j]]]]))

In [16]:
str(a.dtype)

'torch.complex64'